### PR TITLE
Support for Google Cloud STT

### PR DESCRIPTION
**Pull request by daniele-athome**
I'll make another PR with documentation if you are interested in this patch.
I'm unsure on how to use the language code from the profile (e.g. "en") when Google APIs need a locale code (e.g. "en-US"). Do I have that information in the profile?

### CODE REVIEW

**Comment by synesthesiam** [comment]
I've added a "locale" field to the profiles with values like `fr_FR` and `en_US`. Substituting the underscore should get you the correct value for Google STT.

Would you like to add that in before this is merged?

**Comment by daniele-athome** [comment]
> Would you like to add that in before this is merged?

Sure! I've modified the PR.

**Comment by daniele-athome** [comment]
I've added documentation.

**Comment by synesthesiam** [comment]
Looks great, thank you very much!

**Comment by daniele-athome** [comment]
I realized I've made a mistake in the log message for the documentation commit: "TTS" instead of "STT". Sorry... you can fix it if you'd like.

**Pull request merged**
